apiVersion: apps/v1
kind: Deployment
metadata:
  name: repeater-app-{{APP_ENV}}
  namespace: {{APP_ENV}}
  labels:
    app: repeater-app-{{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repeater-app-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: repeater-app-{{APP_ENV}}
    spec:
      containers:
        - name: repeater-app-{{APP_ENV}}-1
          image: {{REPEATER_IMAGE}}
          volumeMounts:
            - name: repeater-token
              mountPath: "/app/secrets/"
              readOnly: true
        - name: repeater-app-{{APP_ENV}}-2
          image: {{REPEATER_IMAGE}}
          volumeMounts:
            - name: repeater-token2
              mountPath: "/app/secrets2/"
              readOnly: true
      volumes:
        - name: repeater-token
          secret:
            secretName: apikey
            items:
              - key: token
                path: "key.py"
        - name: repeater-token2
          secret:
            secretName: apisecret
            items:
              - key: token2
                path: "key2.py"