apiVersion: v1
kind: Secret
metadata:
  name: apikey
  namespace: {{APP_ENV}}
type: Opaque
data:
  token: {{APIKEY}}
---
apiVersion: v1
kind: Secret
metadata:
  name: apisecret
  namespace: {{APP_ENV}}
type: Opaque
data:
  token: {{APISECRET}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: repeater-app-{{APP_ENV}}
  namespace: {{APP_ENV}}
  labels:
    app: repeater-app-{{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repeater-app-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: repeater-app-{{APP_ENV}}
    spec:
      containers:
        - name: repeater-app-{{APP_ENV}}
          image: {{REPEATER_IMAGE}}
          volumeMounts:
            - name: repeater-token
              mountPath: "/app/secrets"
              readOnly: true
            - name: repeater-token2
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: repeater-token
          secret:
            secretName: apikey
            items:
                path: "key.py"
        - name: repeater-token2
          secret:
            secretName: apisecret
            items:
                path: "key2.py"