apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  apikey: base64EncodedValue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repeater-app-{{APP_ENV}}
  namespace: {{APP_ENV}}
  labels:
    app: repeater-app-{{APP_ENV}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repeater-app-{{APP_ENV}}
  template:
    metadata:
      labels:
        app: repeater-app-{{APP_ENV}}
    spec:
      containers:
        - name: repeater-app-{{APP_ENV}}
          image: {{REPEATER_IMAGE}}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: apikey
