apiVersion: v1
kind: Secret
metadata:
  name: apikey
  namespace: {{APP_ENV}}
type: Opaque
data:
  token: {{APIKEY}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
    spec:
      containers:
        - name: repeater-app-{{APP_ENV}}
          image: {{REPEATER_IMAGE}}
          volumeMounts:
            - name: repeater-token
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: repeater-token
          secret:
            secretName: apikey
            items:
              - key: token
                path: "key.py"